import dotenv from 'dotenv';

dotenv.config();

// Brevo SMTP Configuration
const BREVO_CONFIG = {
  apiKey: process.env.BREVO_API_KEY || 'yTcSL0hbzBF1Prqk',
  senderEmail: process.env.BREVO_SENDER_EMAIL || 'pavan@afterburn.fit',
  senderName: 'Afterburn Cafe',
};

/**
 * Send nutrition chart email via Brevo API
 * @param {Object} params - Email parameters
 * @param {string} params.to - Recipient email
 * @param {string} params.dishName - Name of the dish
 * @param {number} params.totalCalories - Total calories
 * @param {Array} params.ingredients - Array of ingredients with calories
 * @param {Object} params.macros - Macro nutrients (protein, carbs, fat, fiber)
 * @returns {Promise<Object>} - Result of email send
 */
export const sendNutritionChartEmail = async ({ to, dishName, totalCalories, ingredients, macros }) => {
  try {
    // Format ingredients list for email
    const ingredientsList = ingredients
      .map(ing => `  • ${ing.name} (${ing.quantity}${ing.unit}): ${ing.calories} cal`)
      .join('\n');

    // Format macros
    const macrosList = `
  • Protein: ${macros.protein}g
  • Carbs: ${macros.carbs}g
  • Fat: ${macros.fat}g
  • Fiber: ${macros.fiber}g`;

    const subject = `Nutrition Analysis: ${dishName} - Afterburn`;
    const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #f97316 0%, #ea580c 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
    .header h1 { margin: 0; font-size: 28px; }
    .header .brand { font-size: 14px; margin-top: 5px; opacity: 0.9; }
    .content { background: #fff; padding: 30px; border: 1px solid #e5e7eb; border-top: none; }
    .calories-box { background: linear-gradient(135deg, #fff7ed 0%, #fed7aa 100%); border: 2px solid #f97316; padding: 20px; text-align: center; border-radius: 10px; margin: 20px 0; }
    .calories-box .number { font-size: 48px; font-weight: bold; color: #f97316; margin: 10px 0; }
    .section { margin: 25px 0; }
    .section h2 { color: #f97316; font-size: 20px; margin-bottom: 15px; border-bottom: 2px solid #f97316; padding-bottom: 5px; }
    .ingredient-list { background: #f9fafb; padding: 15px; border-radius: 8px; font-family: monospace; font-size: 14px; }
    .macros-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin-top: 15px; }
    .macro-card { background: #f0fdf4; border: 1px solid #86efac; padding: 15px; border-radius: 8px; text-align: center; }
    .macro-card .label { font-size: 12px; color: #166534; text-transform: uppercase; }
    .macro-card .value { font-size: 24px; font-weight: bold; color: #15803d; margin-top: 5px; }
    .footer { text-align: center; padding: 20px; color: #6b7280; font-size: 14px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🔥 ${dishName}</h1>
      <div class="brand">Nutrition Analysis by <strong>Afterburn</strong></div>
    </div>
    
    <div class="content">
      <div class="calories-box">
        <div style="font-size: 14px; color: #9a3412; font-weight: 600;">TOTAL CALORIES</div>
        <div class="number">${totalCalories}</div>
        <div style="font-size: 12px; color: #9a3412;">kcal per serving</div>
      </div>

      <div class="section">
        <h2>📊 Ingredient Breakdown</h2>
        <div class="ingredient-list">${ingredientsList}</div>
      </div>

      <div class="section">
        <h2>🥗 Macro Nutrients</h2>
        <div class="macros-grid">
          <div class="macro-card">
            <div class="label">💪 Protein</div>
            <div class="value">${macros.protein}g</div>
          </div>
          <div class="macro-card">
            <div class="label">🍚 Carbs</div>
            <div class="value">${macros.carbs}g</div>
          </div>
          <div class="macro-card">
            <div class="label">🥑 Fat</div>
            <div class="value">${macros.fat}g</div>
          </div>
          <div class="macro-card">
            <div class="label">🌾 Fiber</div>
            <div class="value">${macros.fiber}g</div>
          </div>
        </div>
      </div>
    </div>

    <div class="footer">
      <p>This nutrition analysis was generated by <strong>Afterburn Cafe</strong></p>
      <p style="font-size: 12px; color: #9ca3af;">Powered by professional nutrition tracking</p>
    </div>
  </div>
</body>
</html>`;

    const textBody = `
NUTRITION ANALYSIS: ${dishName}
By Afterburn

TOTAL CALORIES: ${totalCalories} kcal per serving

INGREDIENT BREAKDOWN:
${ingredientsList}

MACRO NUTRIENTS:
${macrosList}

---
This nutrition analysis was generated by Afterburn Cafe
`;

    // Send email via Brevo API
    const response = await fetch('https://api.brevo.com/v3/smtp/email', {
      method: 'POST',
      headers: {
        'accept': 'application/json',
        'api-key': BREVO_CONFIG.apiKey,
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        sender: {
          name: BREVO_CONFIG.senderName,
          email: BREVO_CONFIG.senderEmail,
        },
        to: [
          {
            email: to,
            name: to.split('@')[0],
          },
        ],
        subject,
        htmlContent: htmlBody,
        textContent: textBody,
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Brevo API error: ${error.message || response.statusText}`);
    }

    const result = await response.json();
    console.log('Email sent successfully to:', to, 'Message ID:', result.messageId);

    return {
      success: true,
      message: 'Email sent successfully',
      data: result
    };
  } catch (error) {
    console.error('Error in sendNutritionChartEmail:', error);
    throw error;
  }
};

export default {
  sendNutritionChartEmail
};
