export const inventoryTemplate = [
  // Dry Store
  { name: 'All Purpose Flour', unit: 'gm', category: 'Dry Store', minStock: 10000 },
  { name: 'Wheat Flour', unit: 'gm', category: 'Dry Store', minStock: 5000 },
  { name: 'Maida', unit: 'gm', category: 'Dry Store', minStock: 5000 },
  { name: 'Rice', unit: 'gm', category: 'Dry Store', minStock: 10000 },
  { name: 'Sugar', unit: 'gm', category: 'Dry Store', minStock: 10000 },
  { name: 'Salt', unit: 'gm', category: 'Dry Store', minStock: 5000 },
  { name: 'Coffee Powder', unit: 'gm', category: 'Dry Store', minStock: 2000 },
  { name: 'Tea Powder', unit: 'gm', category: 'Dry Store', minStock: 2000 },
  { name: 'Cocoa Powder', unit: 'gm', category: 'Dry Store', minStock: 1000 },
  { name: 'Baking Powder', unit: 'gm', category: 'Dry Store', minStock: 1000 },
  { name: 'Baking Soda', unit: 'gm', category: 'Dry Store', minStock: 500 },
  { name: 'Yeast', unit: 'gm', category: 'Dry Store', minStock: 500 },
  { name: 'Pasta', unit: 'gm', category: 'Dry Store', minStock: 3000 },
  { name: 'Noodles', unit: 'gm', category: 'Dry Store', minStock: 3000 },
  { name: 'Oats', unit: 'gm', category: 'Dry Store', minStock: 2000 },
  { name: 'Cornflakes', unit: 'gm', category: 'Dry Store', minStock: 2000 },
  { name: 'Bread Crumbs', unit: 'gm', category: 'Dry Store', minStock: 1000 },
  { name: 'Semolina (Rava)', unit: 'gm', category: 'Dry Store', minStock: 2000 },
  
  // Spices & Seasonings
  { name: 'Black Pepper', unit: 'gm', category: 'Dry Store', minStock: 500 },
  { name: 'Red Chilli Powder', unit: 'gm', category: 'Dry Store', minStock: 1000 },
  { name: 'Turmeric Powder', unit: 'gm', category: 'Dry Store', minStock: 500 },
  { name: 'Coriander Powder', unit: 'gm', category: 'Dry Store', minStock: 500 },
  { name: 'Cumin Powder', unit: 'gm', category: 'Dry Store', minStock: 500 },
  { name: 'Garam Masala', unit: 'gm', category: 'Dry Store', minStock: 500 },
  { name: 'Cumin Seeds', unit: 'gm', category: 'Dry Store', minStock: 500 },
  { name: 'Mustard Seeds', unit: 'gm', category: 'Dry Store', minStock: 300 },
  { name: 'Cinnamon', unit: 'gm', category: 'Dry Store', minStock: 200 },
  { name: 'Cardamom', unit: 'gm', category: 'Dry Store', minStock: 200 },
  { name: 'Cloves', unit: 'gm', category: 'Dry Store', minStock: 100 },
  { name: 'Bay Leaves', unit: 'gm', category: 'Dry Store', minStock: 100 },
  { name: 'Oregano', unit: 'gm', category: 'Dry Store', minStock: 200 },
  { name: 'Basil (Dried)', unit: 'gm', category: 'Dry Store', minStock: 200 },
  { name: 'Chilli Flakes', unit: 'gm', category: 'Dry Store', minStock: 300 },
  { name: 'Mixed Herbs', unit: 'gm', category: 'Dry Store', minStock: 200 },
  
  // Oils & Condiments
  { name: 'Vegetable Oil', unit: 'ml', category: 'Dry Store', minStock: 10000 },
  { name: 'Olive Oil', unit: 'ml', category: 'Dry Store', minStock: 2000 },
  { name: 'Butter', unit: 'gm', category: 'Refrigerated', minStock: 3000 },
  { name: 'Ghee', unit: 'gm', category: 'Dry Store', minStock: 2000 },
  { name: 'Vinegar', unit: 'ml', category: 'Dry Store', minStock: 1000 },
  { name: 'Soy Sauce', unit: 'ml', category: 'Dry Store', minStock: 1000 },
  { name: 'Tomato Ketchup', unit: 'gm', category: 'Refrigerated', minStock: 2000 },
  { name: 'Mayonnaise', unit: 'gm', category: 'Refrigerated', minStock: 2000 },
  { name: 'Mustard Sauce', unit: 'gm', category: 'Refrigerated', minStock: 1000 },
  { name: 'Hot Sauce', unit: 'ml', category: 'Dry Store', minStock: 500 },
  { name: 'Honey', unit: 'gm', category: 'Dry Store', minStock: 1000 },
  { name: 'Jam', unit: 'gm', category: 'Refrigerated', minStock: 1000 },
  { name: 'Peanut Butter', unit: 'gm', category: 'Dry Store', minStock: 1000 },
  
  // Fresh Produce - Vegetables
  { name: 'Onions', unit: 'gm', category: 'Fresh Produce', minStock: 10000 },
  { name: 'Tomatoes', unit: 'gm', category: 'Fresh Produce', minStock: 10000 },
  { name: 'Potatoes', unit: 'gm', category: 'Fresh Produce', minStock: 15000 },
  { name: 'Garlic', unit: 'gm', category: 'Fresh Produce', minStock: 2000 },
  { name: 'Ginger', unit: 'gm', category: 'Fresh Produce', minStock: 2000 },
  { name: 'Green Chillies', unit: 'gm', category: 'Fresh Produce', minStock: 1000 },
  { name: 'Carrots', unit: 'gm', category: 'Fresh Produce', minStock: 5000 },
  { name: 'Cabbage', unit: 'gm', category: 'Fresh Produce', minStock: 3000 },
  { name: 'Cauliflower', unit: 'gm', category: 'Fresh Produce', minStock: 3000 },
  { name: 'Capsicum', unit: 'gm', category: 'Fresh Produce', minStock: 3000 },
  { name: 'Beans', unit: 'gm', category: 'Fresh Produce', minStock: 2000 },
  { name: 'Peas', unit: 'gm', category: 'Fresh Produce', minStock: 2000 },
  { name: 'Broccoli', unit: 'gm', category: 'Fresh Produce', minStock: 2000 },
  { name: 'Mushrooms', unit: 'gm', category: 'Fresh Produce', minStock: 2000 },
  { name: 'Spinach', unit: 'gm', category: 'Fresh Produce', minStock: 2000 },
  { name: 'Lettuce', unit: 'gm', category: 'Fresh Produce', minStock: 2000 },
  { name: 'Cucumber', unit: 'gm', category: 'Fresh Produce', minStock: 3000 },
  { name: 'Beetroot', unit: 'gm', category: 'Fresh Produce', minStock: 2000 },
  { name: 'Coriander Leaves', unit: 'gm', category: 'Fresh Produce', minStock: 1000 },
  { name: 'Mint Leaves', unit: 'gm', category: 'Fresh Produce', minStock: 500 },
  { name: 'Curry Leaves', unit: 'gm', category: 'Fresh Produce', minStock: 300 },
  
  // Fruits
  { name: 'Bananas', unit: 'gm', category: 'Fruits', minStock: 5000 },
  { name: 'Apples', unit: 'gm', category: 'Fruits', minStock: 5000 },
  { name: 'Oranges', unit: 'gm', category: 'Fruits', minStock: 5000 },
  { name: 'Lemons', unit: 'gm', category: 'Fruits', minStock: 3000 },
  { name: 'Watermelon', unit: 'gm', category: 'Fruits', minStock: 5000 },
  { name: 'Papaya', unit: 'gm', category: 'Fruits', minStock: 3000 },
  { name: 'Pineapple', unit: 'gm', category: 'Fruits', minStock: 3000 },
  { name: 'Grapes', unit: 'gm', category: 'Fruits', minStock: 2000 },
  { name: 'Strawberries', unit: 'gm', category: 'Fruits', minStock: 2000 },
  { name: 'Mangoes', unit: 'gm', category: 'Fruits', minStock: 3000 },
  { name: 'Pomegranate', unit: 'gm', category: 'Fruits', minStock: 2000 },
  
  // Refrigerated Items
  { name: 'Milk', unit: 'ml', category: 'Refrigerated', minStock: 20000 },
  { name: 'Cream', unit: 'ml', category: 'Refrigerated', minStock: 3000 },
  { name: 'Yogurt', unit: 'gm', category: 'Refrigerated', minStock: 5000 },
  { name: 'Cheese (Cheddar)', unit: 'gm', category: 'Refrigerated', minStock: 2000 },
  { name: 'Cheese (Mozzarella)', unit: 'gm', category: 'Refrigerated', minStock: 2000 },
  { name: 'Paneer', unit: 'gm', category: 'Refrigerated', minStock: 3000 },
  { name: 'Eggs', unit: 'pcs', category: 'Refrigerated', minStock: 100 },
  { name: 'Chicken', unit: 'gm', category: 'Refrigerated', minStock: 5000 },
  { name: 'Fish', unit: 'gm', category: 'Refrigerated', minStock: 3000 },
  { name: 'Prawns', unit: 'gm', category: 'Refrigerated', minStock: 2000 },
  { name: 'Mutton', unit: 'gm', category: 'Refrigerated', minStock: 3000 },
  
  // Frozen Items
  { name: 'Frozen Peas', unit: 'gm', category: 'Frozen', minStock: 3000 },
  { name: 'Frozen Corn', unit: 'gm', category: 'Frozen', minStock: 3000 },
  { name: 'Frozen Mixed Vegetables', unit: 'gm', category: 'Frozen', minStock: 5000 },
  { name: 'Ice Cream (Vanilla)', unit: 'ml', category: 'Frozen', minStock: 5000 },
  { name: 'Ice Cream (Chocolate)', unit: 'ml', category: 'Frozen', minStock: 5000 },
  { name: 'Ice Cream (Strawberry)', unit: 'ml', category: 'Frozen', minStock: 3000 },
  { name: 'Frozen French Fries', unit: 'gm', category: 'Frozen', minStock: 5000 },
  
  // Beverages
  { name: 'Mineral Water', unit: 'ml', category: 'Dry Store', minStock: 50000 },
  { name: 'Soft Drinks (Coke)', unit: 'ml', category: 'Dry Store', minStock: 20000 },
  { name: 'Soft Drinks (Sprite)', unit: 'ml', category: 'Dry Store', minStock: 20000 },
  { name: 'Fruit Juice (Orange)', unit: 'ml', category: 'Refrigerated', minStock: 10000 },
  { name: 'Fruit Juice (Apple)', unit: 'ml', category: 'Refrigerated', minStock: 10000 },
  { name: 'Fruit Juice (Mixed)', unit: 'ml', category: 'Refrigerated', minStock: 10000 },
  
  // Bakery Supplies
  { name: 'Bread (White)', unit: 'slice', category: 'Dry Store', minStock: 20 },
  { name: 'Bread (Brown)', unit: 'slice', category: 'Dry Store', minStock: 15 },
  { name: 'Burger Buns', unit: 'pcs', category: 'Dry Store', minStock: 50 },
  { name: 'Hot Dog Buns', unit: 'pcs', category: 'Dry Store', minStock: 30 },
  { name: 'Pizza Base', unit: 'pcs', category: 'Frozen', minStock: 20 },
  { name: 'Puff Pastry', unit: 'gm', category: 'Frozen', minStock: 2000 },
  
  // Pulses & Lentils
  { name: 'Toor Dal', unit: 'gm', category: 'Dry Store', minStock: 5000 },
  { name: 'Moong Dal', unit: 'gm', category: 'Dry Store', minStock: 3000 },
  { name: 'Chana Dal', unit: 'gm', category: 'Dry Store', minStock: 3000 },
  { name: 'Urad Dal', unit: 'gm', category: 'Dry Store', minStock: 3000 },
  { name: 'Masoor Dal', unit: 'gm', category: 'Dry Store', minStock: 3000 },
  { name: 'Rajma', unit: 'gm', category: 'Dry Store', minStock: 2000 },
  { name: 'Chickpeas', unit: 'gm', category: 'Dry Store', minStock: 3000 },
  
  // Canned & Packaged
  { name: 'Tomato Puree', unit: 'gm', category: 'Dry Store', minStock: 3000 },
  { name: 'Tomato Paste', unit: 'gm', category: 'Dry Store', minStock: 2000 },
  { name: 'Coconut Milk', unit: 'ml', category: 'Dry Store', minStock: 3000 },
  { name: 'Condensed Milk', unit: 'gm', category: 'Dry Store', minStock: 2000 },
  
  // Paper & Disposables
  { name: 'Tissue Paper', unit: 'pcs', category: 'Dry Store', minStock: 50 },
  { name: 'Paper Napkins', unit: 'pcs', category: 'Dry Store', minStock: 500 },
  { name: 'Disposable Plates', unit: 'pcs', category: 'Dry Store', minStock: 200 },
  { name: 'Disposable Cups', unit: 'pcs', category: 'Dry Store', minStock: 200 },
  { name: 'Plastic Spoons', unit: 'pcs', category: 'Dry Store', minStock: 200 },
  { name: 'Plastic Forks', unit: 'pcs', category: 'Dry Store', minStock: 200 },
  { name: 'Takeaway Boxes', unit: 'pcs', category: 'Dry Store', minStock: 100 },
  { name: 'Aluminum Foil', unit: 'pcs', category: 'Dry Store', minStock: 10 },
  { name: 'Cling Film', unit: 'pcs', category: 'Dry Store', minStock: 10 },
  
  // Cleaning Supplies
  { name: 'Dish Soap', unit: 'ml', category: 'Dry Store', minStock: 5000 },
  { name: 'Floor Cleaner', unit: 'ml', category: 'Dry Store', minStock: 5000 },
  { name: 'Hand Wash', unit: 'ml', category: 'Dry Store', minStock: 3000 },
  { name: 'Sanitizer', unit: 'ml', category: 'Dry Store', minStock: 3000 },
  { name: 'Garbage Bags', unit: 'pcs', category: 'Dry Store', minStock: 100 },
  { name: 'Sponges', unit: 'pcs', category: 'Dry Store', minStock: 20 },
  { name: 'Kitchen Towels', unit: 'pcs', category: 'Dry Store', minStock: 30 },
];
